# REF: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-actions-up-to-date-with-dependabot
version: 2
updates:
  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Enable package updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    labels:
      - "node.js"
      - "dependencies"

  # Enable version updates for Go Lang
  - package-ecosystem: "gomod"
    # Look for `go.mod` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for `pyproject.toml`, `requirements.txt`, and `setup.py` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
