name: Check Shell Scripts
on:
  pull_request:

jobs:
  shell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: "**/*.sh"
          files_ignore: |
            ".github/**/*
            .vendor/**/*"
            vendor/**/*"

      - uses: docker://koalaman/shellcheck:stable
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        id: shell-check
        with:
          args: --severity=warning --color=always ${{ steps.changed-files.outputs.all_changed_files }}
